name: Integration Tests

on:
  push:
    branches: [ server ]
  pull_request:
    branches: [ server ]

env:
  DB_CONNECTION: ${{ secrets.DB_CONNECTION }}

jobs:
  Code-Coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci --prefix server
      - run: npm run coverage --prefix server
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: server/coverage/lcov.info
          name: codecov-cooken
          root_dir: server
