name: Coveralls Sync

on:
  push:
    branches: [ server ]
  pull_request:
    branches: [ server ]

jobs:
  Code-Coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci --prefix server
      - run: npm run coverage --prefix server
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./server/coverage/lcov.info"
        env:
          DB_CONNECTION: mongodb://4.tcp.ngrok.io:11440
#          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
